# Site settings
title: Multipath TCP simulator for the Network Simulator ns3
email: matthieu.coudron@lip6.fr
description: > # this means to ignore newlines until "baseurl:"
  This website presents a set of modifications done to the ns3 simulator in order to simulate Multipath TCP. It also contains links to modifications of other programs related to MPTCP analysis such as ns3 DCE or wireshark etc...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mptcp-ns3.lip6.fr" # the base hostname & protocol for your site
github_username:  lip6-mptcp

# Build settings
markdown: kramdown
